services:
  # Cấu hình cho PostgreSQL
  postgres_db:
    image: pgvector/pgvector:pg14
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-my_postgres_db}
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Cấu hình cho MySQL
  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-my_mysql_db}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password123}
    ports:
      - "${MYSQL_PORT:-3309}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  # Cấu hình cho Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_portal_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-my_postgres_db}
      - DB_USERNAME=${POSTGRES_USER:-admin}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password123}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS:-86400000}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    depends_on:
      - postgres_db
    restart: always

volumes:
  postgres_data:
  mysql_data: