DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255),
    address VARCHAR(30),
    phone VARCHAR(10),
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(50),
    password VARCHAR(255),
    role VARCHAR(50) DEFAULT 'ROLE_PATIENT',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL
);